# Generated by Django 2.0.2 on 2018-04-12 17:12

from django.db import migrations, models
import recipe_book.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe_book.Recipe_ingredient', to='recipe_book.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=recipe_book.utils.FilePathGenerator()),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=recipe_book.utils.FilePathGenerator()),
        ),
    ]
